### ISSUE TITLE
MSBuild log generated by StyleCop throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by brianfeucht** [cake-contrib/Cake.Issues.MsBuild#80] opened 2019-03-11 23:25 UTC
The following Xml MSBuild log causes an `System.ArgumentOutOfRangeException` : `startIndex cannot be larger than length of string.` 

```
<?xml version="1.0" encoding="utf-8"?>
<build started="3/11/2019 22:29:45">
  <warning code="SA1633" file="File.cs" line="1" column="1" started="3/11/2019 22:29:59"><![CDATA[The file header is missing or not located at the top of the file.]]></warning>
</build>
```

**Comment by brianfeucht** [comment] 2019-03-11 23:29
Unit test to reproduce the error:
https://github.com/brianfeucht/Cake.Issues.MsBuild/commit/8bb38b6eeec95850b45349cbb3a180aa8402e991

**Comment by pascalberger** [comment] 2019-03-12 07:59
@brianfeucht Thanks for the report and test case. 

Can you create a PR with the test case. Then I can implement the fix for this on top of it on your branch (or you can of course also directly provide the implementation in the PR if you want)

**Comment by brianfeucht** [comment] 2019-03-12 14:19
@pascalberger PR created.  

I may get time to implement a fix today, but poking at it last night it wasn't 100% clear the best way to achieve that yet.

It is throwing due to the repository URL being longer than the local file path at https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/22adbbb3e4ab8e85bb4b2bb32768d3ce4d300bf3/src/Cake.Issues.MsBuild/BaseMsBuildLogFileFormat.cs#L80

I think this code would need to check that the string starts with the repository url before doing the `substring`.  However, we'd need to standardize the path separators before doing as one string has `/` and the other has `\\`

**Comment by pascalberger** [comment] 2019-03-12 20:21
@brianfeucht On which OS are you running it?

In my environment test case works as expected:

1. It tries to read the file from the logfile: https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/22adbbb3e4ab8e85bb4b2bb32768d3ce4d300bf3/src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs#L56
2. It won't find a parent compile task so it skips this part and file name is just `File.cs`:
https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/22adbbb3e4ab8e85bb4b2bb32768d3ce4d300bf3/src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs#L211-L216
3. It will validate the file name:
https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/22adbbb3e4ab8e85bb4b2bb32768d3ce4d300bf3/src/Cake.Issues.MsBuild/LogFileFormat/XmlFileLoggerLogFileFormat.cs#L221
4. There it will see that file is not part of the repository and therefore exit and ignore this warning:
https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/22adbbb3e4ab8e85bb4b2bb32768d3ce4d300bf3/src/Cake.Issues.MsBuild/BaseMsBuildLogFileFormat.cs#L31-L34

The call to the `MakeFilePathRelativeToRepositoryRoot` method comes after the check if the file is part of the repository and is not called on my environment:

https://github.com/cake-contrib/Cake.Issues.MsBuild/blob/22adbbb3e4ab8e85bb4b2bb32768d3ce4d300bf3/src/Cake.Issues.MsBuild/BaseMsBuildLogFileFormat.cs#L37

**Comment by brianfeucht** [comment] 2019-03-12 20:34
I am on Window 10.  Running the test via `Visual Studio 16.0.0.0 Preview 3` and `DotCover`

This also fails running via the CAKE script on Powershell using MSBuild

Doing a bit of debugging based on those details:

2.  `parentFileAttr` is null
4.  `CheckIfFileIsInRepository` is returning true:
   `filePath.IsSubpathOf(repositorySettings.RepositoryRoot.FullPath)`  returns true
   `"File.cs".IsSubpathOf("c:/Source/Cake.Issues.MsBuild")` returns true

**Comment by pascalberger** [comment] 2019-03-12 21:49
Interesting, `CheckIfFileIsInRepository`, or rather the `IsSubpathOf` call, should return `false` (and does on my machine).

**Comment by pascalberger** [comment] 2019-03-12 21:59
On Azure Pipelines the test also [fails because it doesn't return an issue](https://dev.azure.com/cake-contrib/Cake.Issues.MsBuild/_build/results?buildId=725&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=c37637b8-ed57-5a02-c556-da2855a7e2d3&lineStart=616&lineEnd=619&colStart=1&colEnd=2) and not with an `ArgumentOutOfRangeException`.

**Comment by pascalberger** [comment] 2019-03-12 22:19
The only case I see when `"File.cs".IsSubpathOf("c:/Source/Cake.Issues.MsBuild")` returns `true` is when the current working directory is `c:\Source\Cake.Issues.MsBuild`. But I fail to see yet why this happens in your case.

**Comment by brianfeucht** [comment] 2019-03-12 22:46
When I put a stop point at `filePath.IsSubpathOf(repositorySettings.RepositoryRoot.FullPath)` and run `System.IO.Directory.GetCurrentDirectory()` in the intermediate window, I get `"C:\\source\\Cake.Issues.MsBuild\\src\\Cake.Issues.MsBuild.Tests\\bin\\Debug\\netcoreapp2.0"` 🤔

**Comment by brianfeucht** [comment] 2019-03-13 18:46
I've been able to track this down further.  The issue is indeed related to the working directory.  

https://github.com/cake-contrib/Cake.Issues/blob/76456cabb492c60be2932023c5c7c94af9412509/src/Cake.Issues/StringPathExtensions.cs#L71

This appears to prepend the CurrentWorking directory to the file name in the case of relative files.  In my build environment this is set to the same as the Repository directory.  If I call `System.IO.Directory.SetCurrentDirectory` to a directory outside my Repository I do not get an exception (giving me a work around for now)

I've updated my PR to hopefully make this reproduce for you.

**Comment by pascalberger** [comment] 2019-03-14 19:58
Yeah, it's caused by the working directory since [Path.GetFullPath](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netframework-4.7.2) is used. 

The point which I don't understand is why you're running into this issue, or is `c:\Source\Cake.Issues.MsBuild` you actual path where you have cloned the repo to?

**Comment by brianfeucht** [comment] 2019-03-14 20:00
Yes, I've cloned my repo to `c:\Source\Cake.Issues.MsBuild`

**Comment by pascalberger** [comment] 2019-03-17 16:31
@brianfeucht I've updated #81 to contain a fix for the issue. Can you please test it and report back if it solves your issue. 

If it works for you I'll merge the PR and create a release

**Comment by brianfeucht** [comment] 2019-03-18 16:13
@pascalberger I have confirmed this change resolves the issue in my code base where I first ran into it.  🍻 thank you!

**Closed** 2019-03-18 16:56 UTC
Labels: Bug

**Comment by pascalberger** [comment] 2019-03-18 18:46
@brianfeucht Release 0.6.3 is now building and should be available soon on nuget.org

Thanks for reporting this and helping tracking it down. Really appreciated.
